service: notification-service

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:SetSMSAttributes
            - sns:Publish
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "*"
          
functions:
    sendSMS:
        handler: lambdas/endpoints/sendSMS.handler
        events:
            - http:
                  path: send-sms
                  method: POST
                  cors: true

    verifySMS:
        handler: lambdas/endpoints/verifySMS.handler
        events:
            - http:
                  path: verify-sms
                  method: POST
                  cors: true