service: withdrawal-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [WithDrawalResource, Arn]
            - arn:aws:dynamodb:us-east-2:945677977841:table/Asset
            - arn:aws:dynamodb:us-east-2:945677977841:table/Transaction

  httpApi:
    cors: true

functions:
  withdrawal:
    handler: withdrawal.handler
    events:
      - httpApi:
          path: /withdrawal
          method: post

  get-withdrawal:
    handler: get.handler
    events:
      - httpApi:
          path: /get-withdrawal/{id}
          method: get

resources:
  Resources:
    WithDrawalResource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WithDrawal
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3

plugins:
  - serverless-offline
