org: rajatdua
app: aws-node-http-api-project
service: mock
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ${file(../serverless-config.json):region}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
resources:
Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${opt:stage, self:provider.stage}
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
