service: my-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${file(../serverless-config.json):stage}
  region: ${file(../serverless-config.json):region}

functions:
  storeIPAddress:
    handler: storeapi.storeIPAddress
    events:
      - http:
          path: store-ip
          method: post
          cors: true

plugins:
  - serverless-offline