service: stake-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [StakeResource, Arn]
            - arn:aws:dynamodb:us-east-2:945677977841:table/Asset
            - arn:aws:dynamodb:us-east-2:945677977841:table/Transaction

  httpApi:
    cors: true

functions:
  create-stake:
    handler: create.handler
    events:
      - httpApi:
          path: /stake
          method: post


resources:
  Resources:
    StakeResource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Stakes
        AttributeDefinitions:
          - AttributeName: stk_id
            AttributeType: S
        KeySchema:
          - AttributeName: stk_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3

plugins:
  - serverless-offline
