service: asset-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [AssetTable, Arn]
            - arn:aws:dynamodb:us-east-2:945677977841:table/Wallet
  httpApi:
    cors: true

functions:
  create-asset:
    handler: create.handler
    events:
      - httpApi:
          path: /asset
          method: post
  list-asset:
    handler: list.handler
    events:
      - httpApi:
          path: /assets/list/{userId}
          method: get
  delete-asset:
    handler: delete.handler
    events:
      - httpApi:
          path: /assets/{assetId}
          method: delete
  get-asset:
    handler: get.handler
    events:
      - httpApi:
          path: /asset/{assetId}
          method: get

  create-all:
    handler: create-all.handler
    events:
      - httpApi:
          path: /asset/all
          method: post

resources:
  Resources:
    AssetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Asset
        AttributeDefinitions:
          - AttributeName: assetId
            AttributeType: S
        KeySchema:
          - AttributeName: assetId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3

plugins:
  - serverless-offline
