
service: trading-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${file(../serverless-config.json):stage}
  region: ${file(../serverless-config.json):region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [TradingTable, Arn]

  httpApi:
    cors: true
    
Type: AWS::Logs::LogGroup
Properties:
  DataProtectionPolicy: Json
  KmsKeyId: String
  LogGroupName: String
  RetentionInDays: Integer
  Tags:
    - Tag

functions:
  create-sell:
    handler: create.handler
    events:
      - httpApi:
          path: /trade
          method: post
  update-trade:
    handler: update.handler
    events:
      - httpApi:
          path: /trade/{id}
          method: put

  list-trade:
    handler: list.handler
    events:
      - httpApi:
          path: /trade
          method: get

  list-all-trade:
    handler: list-all.handler
    events:
      - httpApi:
          path: /alltrade
          method: get

  trade:
    handler: get.handler
    events:
      - httpApi:
          path: /trade/{id}
          method: get
  
  currency :
      handler: getCurrency.handler
      memorySize: 840
      timeout: 15
      events:
        - httpApi:
            path: /currencies
            method: get

  currency-data :
      handler: updateCurrenciesdata.handler
      memorySize: 840
      timeout: 15
      events:
        - httpApi:
            path: /updateCurrenciesdata
            method: get
  marketplace:
      handler: marketplace.handler
      memorySize: 840
      timeout: 15
      events:
        - httpApi:
            path: /marketplace
            method: get
  market-cap-lct:
      handler: market-cap-lct.handler
      events:
        - httpApi:
            path: /market-cap/lct
            method: get
  marketplace-filter:
      handler: marketplace_filter.handler
      memorySize: 840
      timeout: 15
      events:
        - httpApi:
            path: /marketplace_filter/{name}
            method: get
resources:
  Resources:
    TradingTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: 'trading-offer'
          

plugins:
  - serverless-offline